# Generated by Django 4.0.2 on 2022-04-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='machine_model',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='machine_serial',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
    ]
