# Generated by Django 4.0.2 on 2022-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
